[package]
name = "convert-data-from-ods-into-usv"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.18"
zip = "0.6.2"
